/* Generated By:JavaCC: Do not edit this line. SPLPrimeConstants.java */
package part2_splprime;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPLPrimeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int LEFT_PAREN = 7;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 8;
  /** RegularExpression Id. */
  int LEFTT_BRACE = 9;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MULT = 13;
  /** RegularExpression Id. */
  int DIF = 14;
  /** RegularExpression Id. */
  int SEMICOL = 15;
  /** RegularExpression Id. */
  int NOTEQUALS = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int EQUAL_EQUAL = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 20;
  /** RegularExpression Id. */
  int GREATER = 21;
  /** RegularExpression Id. */
  int LESS_EQUAL = 22;
  /** RegularExpression Id. */
  int LESS = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int PRINT = 30;
  /** RegularExpression Id. */
  int VAR = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int STRING = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "<NOTEQUALS>",
    "\"!\"",
    "\"==\"",
    "\"=\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "\"and\"",
    "\"else\"",
    "\"false\"",
    "\"true\"",
    "\"if\"",
    "\"or\"",
    "\"print\"",
    "\"var\"",
    "\"while\"",
    "<IDENTIFIER>",
    "<STRING>",
  };

}
